version: '3'
services:
  
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: saiteja
      MYSQL_PASSWORD: saiteja
      MYSQL_DB: my_db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: devops
      MYSQL_DATABASE: my_db
      MYSQL_USER: saiteja
      MYSQL_PASSWORD: saiteja
    volumes:
      - mysql-data:/var/lib/mysql  # Mount the volume for MySQL data storage

volumes:
  mysql-data:
