name: Two-tier Application

 

on:
  push:
    branches: [ master ]

 

jobs:
  Code-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout-Code 
        run: |
          echo "Code Checkout successfully"
  Code_build:
    runs-on: ubuntu-latest
    needs: Code-checkout
    steps:
      - uses: actions/checkout@v2
      - name: Code Build
        run: | 
          echo "Building Code..."
          docker build -t myimage .
  Code_push:
    runs-on: ubuntu-latest
    needs: Code_build
    steps:
      - uses: actions/checkout@v2
      - name: Code Build
        run: | 
          echo "Building Code..."
          docker build -t myimage .
          docker tag myimage saiteja0112/dockerimages:v1
          docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_token }}
          docker push saiteja0112/dockerimages:v1
