name: two-tier application

on:
  push:
    branches:
      - master
jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: code- checkout
        run: |
          echo "Code checkout successfully" 
